### ISSUE TITLE
Warning/error using ruby 2.7.1

### ISSUE THREAD

**Issue by caponecicero** [wizardofosmium/porolog#16]
The attached example from your documentation generates the following when using **_ruby 2.7.1_**:

* `.../gems/porolog-1.0.1/lib/porolog/predicate.rb:88: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

* `.../.gems/gems/porolog-1.0.1/lib/porolog/predicate.rb:74: warning: The called method 'initialize' is defined here`

> **ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]**

Both these messages occur at the following line in the attachment:

`builtin   :gtr, :is, :noteq, :between,  class_base: self`

Changing the signature of `Porolog::Predicate.new` from

`def self.new(*args)`

to

`def self.new(*args, **)`

fixes both these issues.

-- sw

[example4.txt](https://github.com/wizardofosmium/porolog/files/5043754/example4.txt)

**Comment by wizardofosmium** [comment]
Thanks @caponecicero .  I'll update.
